//created on: Sep 27, 2020
package forward

//list any import classes here.
import model.*;
import model.enums.*;

//declare any global variables here



rule "R1 – Nivel de hematocrito bajo" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.hematocrito < 38.3)
    then
      modify($persona) {
            getMuestraDeSangre().setNivelHematocrito(ComponentLevel.Bajo);
        }   
end

rule "R2 – Nivel de hematocrito normal" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.hematocrito >= 38.3 && muestraDeSangre.hematocrito <= 48.6 )
    then
      modify($persona) {
            getMuestraDeSangre().setNivelHematocrito(ComponentLevel.Normal)
        }
end
rule "R3 – Nivel de hematocrito alto" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.hematocrito > 48.6 )
    then
      modify($persona) {
            getMuestraDeSangre().setNivelHematocrito(ComponentLevel.Alto)
        }
end
rule "R4 – Nivel de hemoglobina corspucular media bajo" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.hemoglobinaCorspucularMedia < 27)
    then
      modify($persona) {
            getMuestraDeSangre().setNivelHemoglobinaCorpusculasMedia(ComponentLevel.Bajo)
        }
end
rule "R5 – Nivel de hemoglobina corspucular media normal" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.hemoglobinaCorspucularMedia >= 27 && muestraDeSangre.hemoglobinaCorspucularMedia <= 33 )
    then
      modify($persona) {
            getMuestraDeSangre().setNivelHemoglobinaCorpusculasMedia(ComponentLevel.Normal)
        }
end
rule "R6 – Nivel de hemoglobina corspucular media alto" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.hemoglobinaCorspucularMedia > 33 )
    then
      modify($persona) {
            getMuestraDeSangre().setNivelHemoglobinaCorpusculasMedia(ComponentLevel.Alto)
        }
end
rule "R7 – Nivel de hemoglobina corspucular media alto" lock-on-active
no-loop agenda-group "calculation"
when
    $persona: Persona(muestraDeSangre.volumenCorpuscularMedio < 78.0 )
then
  modify($persona) {
        getMuestraDeSangre().setNivelVolumenCorpuscularMedio(ComponentLevel.Bajo)
    }
end


rule "R8 – Nivel de volumen corpuscular medio normal" lock-on-active
agenda-group "calculation"
when
    $persona: Persona(muestraDeSangre.volumenCorpuscularMedio >= 78.0 && muestraDeSangre.volumenCorpuscularMedio <= 100.0 )
then
  modify($persona) {
        getMuestraDeSangre().setNivelVolumenCorpuscularMedio(ComponentLevel.Normal)
    }
end

rule "R9 – Nivel de volumen corpuscular medio alto" lock-on-active
agenda-group "calculation"
when
    $persona: Persona(muestraDeSangre.volumenCorpuscularMedio > 100.0 )
then
  modify($persona) {
        getMuestraDeSangre().setNivelVolumenCorpuscularMedio(ComponentLevel.Alto)
    }
end
rule "R10 – Nivel de sideremia bajo" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.sideremia < 50)
    then
      modify($persona) {
            getMuestraDeSangre().setNivelSideremia(ComponentLevel.Bajo)
        }
end

rule "R11 – Nivel de sideremia normal" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.sideremia >= 50 && muestraDeSangre.sideremia <= 150 )
    then
      modify($persona) {
            getMuestraDeSangre().setNivelSideremia(ComponentLevel.Normal)
        }
end

rule "R12 – Nivel de sideremia alto" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.sideremia > 50 )
    then
      modify($persona) {
            getMuestraDeSangre().setNivelSideremia(ComponentLevel.Alto)
        }
end
rule "R13 – Nivel de transferrina bajo" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.transferrina < 200)
    then
      modify($persona) {
            getMuestraDeSangre().setNivelTransferrina(ComponentLevel.Bajo)
        }
end

rule "R14 – Nivel de transferrina normal" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.transferrina >= 200 && muestraDeSangre.transferrina <= 360 )
    then
      modify($persona) {
            getMuestraDeSangre().setNivelTransferrina(ComponentLevel.Normal)
        }
end

rule "R15 – Nivel de transferrina alto" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.transferrina > 360 )
    then
      modify($persona) {
            getMuestraDeSangre().setNivelTransferrina(ComponentLevel.Alto)
        }
end
rule "R16 – Nivel de ferritina bajo" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.ferritina < 12)
    then
      modify($persona) {
            getMuestraDeSangre().setNivelFerritina(ComponentLevel.Bajo)
        }
end

rule "R17 – Nivel de ferritina normal" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.ferritina >= 12 && muestraDeSangre.ferritina <= 300 )
    then
      modify($persona) {
            getMuestraDeSangre().setNivelFerritina(ComponentLevel.Normal)
        }
end

rule "R18 – Nivel de ferritina alto" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.ferritina > 300 )
    then
      modify($persona) {
            getMuestraDeSangre().setNivelFerritina(ComponentLevel.Alto)
        }
end
rule "R19 – Nivel de amplitud de distribucion eritrocitaria bajo" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.amplitudDistribucionEritrocitaria < 11)
    then
      modify($persona) {
            getMuestraDeSangre().setNivelAmplitudDistribucionEritrocitaria(ComponentLevel.Bajo)
        }
end

rule "R20 – Nivel de amplitud de distribucion eritrocitaria normal" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.amplitudDistribucionEritrocitaria >= 11 && muestraDeSangre.amplitudDistribucionEritrocitaria <= 14 )
    then
      modify($persona) {
            getMuestraDeSangre().setNivelAmplitudDistribucionEritrocitaria(ComponentLevel.Normal)
        }
end

rule "R21 – Nivel de amplitud de distribucion eritrocitaria alto" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.amplitudDistribucionEritrocitaria > 14 )
    then
      modify($persona) {
            getMuestraDeSangre().setNivelAmplitudDistribucionEritrocitaria(ComponentLevel.Alto)
        }
end
rule "R22 – Nivel de reticulocitos bajo" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.reticulocitos < 35000)
    then
      modify($persona) {
            getMuestraDeSangre().setNivelReticulocitos(ComponentLevel.Bajo)
        }
end

rule "R23 – Nivel de reticulocitos normal" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.reticulocitos >= 35000 && muestraDeSangre.reticulocitos <= 75000 )
    then
      modify($persona) {
            getMuestraDeSangre().setNivelReticulocitos(ComponentLevel.Normal)
        }
end

rule "R24 – Nivel de reticulocitos alto" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.reticulocitos > 75000 )
    then
      modify($persona) {
            getMuestraDeSangre().setNivelReticulocitos(ComponentLevel.Alto)
        }
end

rule "R25 – Nivel de hematies bajo" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.hematies < 4500000)
    then
      modify($persona) {
            getMuestraDeSangre().setNivelHematies(ComponentLevel.Bajo)
        }
end

rule "R26 – Nivel de hematies normal" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.hematies >= 4500000 && muestraDeSangre.hematies <= 5500000 )
    then
      modify($persona) {
            getMuestraDeSangre().setNivelHematies(ComponentLevel.Normal)
        }
end

rule "R27 – Nivel de hematies alto" lock-on-active
agenda-group "calculation"
    when
        $persona: Persona(muestraDeSangre.hematies > 5500000 )
    then
      modify($persona) {
            getMuestraDeSangre().setNivelHematies(ComponentLevel.Alto)
        }
end

rule "R28 – Morfologia anemia microcitica" lock-on-active agenda-group "report"
    when
        $persona: Persona(
            muestraDeSangre.getNivelHematocrito().isa(ComponentLevel.Bajo),
            muestraDeSangre.nivelHemoglobinaCorpusculasMedia.isa(ComponentLevel.Bajo),
            muestraDeSangre.nivelVolumenCorpuscularMedio.isa(ComponentLevel.Bajo)
       )
     
    then
      modify($persona) {
      	getMuestraDeSangre().getTipoAnemia().setMorfologia(AnemiaMorfology.Microcitica);
	  }
end

